title: CSC 397/595 Lab Assignments
description: CSC 397/595 Lab Assignments

baseurl: "/csc-397-595-docs"

remote_theme: JV-conseil/jekyll-theme-read-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown